apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sqjotjb3p-nodejs 
  janus-idp.io/tekton: sqjotjb3p-nodejs
  backstage.io/kubernetes-id: sqjotjb3p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sqjotjb3p-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml